# Generated by Django 4.0.2 on 2022-02-22 07:42

import NewsArticle.models
from django.db import migrations, models

from NewsArticle.db_Script.uploading_news import populate_news


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='News')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=NewsArticle.models.image_path)),
                ('premium_content', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(populate_news)
    ]
